openapi: 3.1.0
info:
  title: GY Messages
  description: Official GYCODING messaging API service.
  version: 1.1.0
servers:
  - url: 'https://api.gycoding.com/messages'
    description: Production Server
paths:
  /messages/{chat-id}/messages/list:
    get:
      summary: List messages
      description: Retrieves the whole list of messages from a specific chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK

  /messages/{chat-id}/delete:
    delete:
      summary: Delete chat
      description: Removes a chat completely, unassigning it from every user.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK

  /messages/{chat-id}/leave:
    delete:
      summary: Leave chat
      description: As a user, leaves a chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK

  /messages/{chat-id}/send:
    post:
      summary: Send message
      description: Sends a message to a specific chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The content of the message.
      responses:
        '200':
          description: OK

  /messages/create:
    post:
      summary: Create chat
      description: Creates a new chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the chat.
      responses:
        '200':
          description: OK

  /messages/{chat-id}/members/add:
    post:
      summary: Add a member
      description: As a user, add myself into a chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK

  /messages/chats/list:
    get:
      summary: List chats
      description: Retrieves the whole list of chat from where the user belongs.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK

  /messages/{chat-id}/members/list:
    get:
      summary: List members
      description: Retrieves the whole list of members from a specific chat.
      parameters:
        - $ref: 'parameters/gy-messages.yml#/components/parameters/chat-id'
        - $ref: 'parameters/gy-messages.yml#/components/parameters/token'
      responses:
        '200':
          description: OK